### PR TITLE
DOMContentLoaded/load timer; name=""

### LINKED ISSUE #14: AOL.com still slips through
**Updated with repro** - Google Chrome Version 67.0.3396.87 (Official Build) (64-bit) on Win8.1 Enterprise x64

The root cause appears to be that AOL takes a really long time to load!

untitled

Steps:

 - Add a new user
 - Say "No thanks" to the sign-in prompt
 - Go to `chrome://extensions` and remove all extensions
 - Go to [the extension page](https://chrome.google.com/webstore/detail/dont-add-custom-search-en/dnodlcololidkjgbpeoleabmkocdhacc) and hit Add to Chrome
 - Approve the permissions box (hit "Add extension")
 - Basic functionality check: go [here](https://files.scene.org) and search for `elevated`.
   - The URL should be `https://files.scene.org/search/?q=elevated&chrome_dont_add_custom_search_engines_srsly=`.
   - If you want a break, download Elevated (2009) and watch it ;) .  Four kilobytes of software generate a 3.5min realtime-rendered video.  [YT](https://www.youtube.com/watch?v=pI2R-35tPy0).  OK, now back to this issue!
   - Go to `chrome://settings/searchEngines` and confirm that `Other search engines` is empty.
 - Go to `https://aol.com`
 - **While the spinner is still running,** put `foo` (or whatever you want) in the Search box at the top of the page and hit Enter.
 - Go to `chrome://settings/searchEngines` and confirm that `Other search engines` lists

        Search engine       Keyword      Query URL
        aol.com             aol.com      https://search.aol.com/aol/search?...

### LINKED ISSUE #15: The name of the added textarea element
In: spoilFormGet()
I have noticed that we can name the new element "" (empty string). The trick still works but nothing appears in the generated url. Could be useful if we don't want to be noticed...
For now, having it named "chrome_dont_add_custom_search_engines_srsly" as a way to notice that the fix worked, is a good idea. But It's something to think about for future versions.

As a side note, I have encountered a site were "if (location.pathname == '/')" (my test version) is not respected by chrome. (cf https://www.chromium.org/tab-to-search # 2 ).
Since every form that fits the rules will see a new element added, name="" can be a way to fly under the radar. Nothing will show in servers' logs.

### PR DESCRIPTION
**Pull request by cxw42**
This is the proposed fix for #14 from @Procyon-b - as zipped [here](https://github.com/gregsadetsky/chrome-dont-add-custom-search-engines/issues/14#issuecomment-399790728).  I am adding the PR since Procyon-b is not able to work on it at this time.

I have not yet tested this, so please try it out and let me know what you find!  Please also check yandex per #16.

Assuming it works, it closes #14 and closes #15.

Before merging, we will need an additional commit to turn off `DEBUG`.

### CODE REVIEW

**Comment by cxw42** [comment]
Works with uk.webuy.com, but doesn't spoil Yandex.

**Comment by Procyon-b** [comment]
I'm back. Finally !  :)

I still have to finalize some configurations, and installation of utilities and I'm ready to go.

**Comment by gregsadetsky** [comment]
@Procyon-b glad to have you back! && Thank you for your work!

**Comment by cxw42** [comment]
Updated per discussion in #16, and looking good to me so far!

**Comment by Procyon-b** [comment]
Question.
I was about to add a pull request for the last version of content.js. I already have a fork (used for my first PR). I see that the branch is 6 commits behind, and "compare" shows nothing. What should I do? Refork? Somehow resync?
Note: I'm using the web interface.

**Comment by cxw42** [comment]
Forks unfortunately don't keep up to date with upstream repositories automatically :( .  The easiest thing might just be to delete your current fork and then re-fork this repo!

I found an extension that claims to update your fork to match master, but I haven't tried it myself - https://chrome.google.com/webstore/detail/github-sync-fork/omjaffmdnnkgmbbjmdalehkjcaklleii/ .  Other thoughts are at:

 - https://github.com/KirstieJane/STEMMRoleModels/wiki/Syncing-your-fork-to-the-original-repository-via-the-browser 
 - https://stackoverflow.com/q/20984802/2877364 
 - https://github.com/isaacs/github/issues/121
 - https://webapps.stackexchange.com/questions/28998/how-do-you-update-a-github-repo-fork-in-the-web-interface

(but note that if you do any of the Web-based options, you need to rebase rather than merging.)

And the official support page, using the CLI: https://help.github.com/articles/syncing-a-fork/

@gregsadetsky have you had a chance to test this PR?  I have been running this code and haven't noticed any issues, but I haven't had a chance to run through the whole list on the wiki and try them out.

**Comment by Procyon-b** [comment]
re. methods to sync:
I'll refork, this is the easiest way for the moment. I asked before doing this in case there was a simpler method I didn't notice. 
What do you do in GitHub desktop? If that's what you are using.

re. Testing.
I have tested on several sites mentionned here and there with the version before the latest little fix. I don't remember if I used a list.

**Comment by cxw42** [comment]
@Procyon-b I use the command line - I have [Cygwin](https://cygwin.com) installed and so do `git pull upstream master` / `git push` to update `origin` (my fork) from `upstream`) (this repo).

**Comment by Procyon-b** [comment]
re: Testing

I remember now using that list to test. I have retried all these hosts and all seems ok.

**Pull request merged**
