### PR TITLE
Fix for duckduck

### PR DESCRIPTION
**Pull request by Procyon-b**
Edit:
I was expecting seeing "Rebase and merge" as [shown here](https://blog.github.com/2016-09-26-rebase-and-merge-pull-requests/) but I must have used too many "shortcuts".

### CODE REVIEW

**Comment by Procyon-b** [comment]
@gregsadetsky @cxw42

Don't forget that this PR has still to end up as a final version. It's the fix for #18 , and possibly other sites.
I have been running it since october without a hitch.

If you haven't tried it yet, I have set up an unlisted extension for a friend who dislikes the developper mode warning. It's exactly the same extension, except for the 2 lines modification.

https://chrome.google.com/webstore/detail/dont-add-custom-search-en/jfcjaalipndkodegjdkogopoaejmemla

**Comment by gregsadetsky** [comment]
Hey,

I just went through my master list of annoying sites, and saw that this PR lets through `https://www.linguee.com` consistently. Load the site and do a search to make sure that the custom search engine gets added.

I also saw `https://abra-electronics.com/` and `https://www.nytimes.com` get added at least once each, but could not reproduce this consistently.

Duck is definitely blocked, so this is great!

**Comment by Procyon-b** [comment]
Hi @gregsadetsky ,
None of these annoyances are targeted by the last fix. They don't use the xml description.
Off the 3, I can only reproduce nytimes by submitting a search. In that particular case, it's because the form element is created when the user clicks the magnifying glass.
A solution is to add a mutation observer, and make it apply the patch to the newly created form.

**Comment by Procyon-b** [comment]
@gregsadetsky 
I have a solution implemented with a MutationObserver, but it can be quite heavy on the page. I don't notice it in the reactivity of the page, or in its load time, but the page adds quit a lot of nodes dynamically, and our content script is checking each for a <form> child.
But it works.

Maybe we could implement this as an option for the user: he can blacklist a site to be handled with a MutationObserver.
I know that a content script can't use extension data at launch time, but since the MutationObserver can be added at any time, it can be done (I think) by sending a message to the background script.

The fact is that I don't know if many sites will fall in the category of `nytimes.com`

**Comment by Procyon-b** [comment]
Note that I can't reproduce with `https://www.linguee.com`. I even tested without uBlockO.
In your test, when is it added to the SE list?  When displayed or when you search something?

**Comment by Procyon-b** [comment]
> Thanks for checking. I'm not sure what to do -- merge this PR (for DDG) but then open other PRs for other sites?

We could merge this PR now. Still I haven't seen any new message reporting problems since version 0.0.5 .  So, appart from DDG and a couple of other sites that are still getting through with 0.0.5 , the new version won't fix many. It's a matter of narrowing the list of exceptions.
> I'm obviously also thinking that automated testing would be great, but it's probably not trivial to implement.

While the list is still short, testing manually is not a problem. But we need to do it with the same method. (checking if SE is added when the page is loaded, and after making a search)

**Comment by gregsadetsky** [comment]
re: linguee -- I just tested again and the search engine is added after doing a search.

**Comment by Procyon-b** [comment]
linguee...
Weird.
Can you verify if the textarea is really added? Right-click/inspect the linguee logo. It is inside the form element. You should immediately see if the new element is there.

**Comment by Procyon-b** [comment]
@gregsadetsky ... linguee

I'll try installing the latest chrome version alongside the version I use now, and test if this is browser related.
What is your current version? I'm still running 70.0.3538.110

**Comment by cxw42** [comment]
@gregsadetsky re. https://github.com/gregsadetsky/chrome-dont-add-custom-search-engines/pull/20#issuecomment-452811674 - yes, I think one PR per site is reasonable, if each site requires different changes.  

Automated testing is open as #7.

**Comment by cxw42** [comment]
I confirm this PR (as implemented in my pr20 branch) does successfully spoil duckduckgo.com and start.duckduckgo.com in my testing to date :) .

**Comment by cxw42** [comment]
@Procyon-b unless I hear from you otherwise in a few days, I'll open a new PR off my branch, close this one, and merge.  If you'd prefer to do so, go for it!  I have not experienced any issues.

**Pull request closed without merging**
